name: Message Regex
on: [push]

jobs:
  build:
    if: "contains(toJSON(github.event.commits.*.message), '[ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Check-out project
      uses: actions/checkout@v1
    - name: Echo Hello
      run: echo 'Hello World !'
